name: meditation_animation_flutter
description: Flutter project animation challenge (Blin Qipa - bqubique - blinnqipa@gmail.com).

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  audioplayers: ^1.1.1
  video_player: ^2.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/sounds/btn_sound.wav
    - assets/videos/bg_video.mp4
  #   - images/a_dot_ham.jpeg
